# Einführung

Das Thema Lohnarbeit wurde seit Beginn der Soziologie als Disziplin immer wieder bearbeitet. Schon bevor sich das Feld der Soziologie herausbildete, befasste sich unter anderem Karl Marx mit der Art und Weise, wie Arbeit und unsere sozialen und wirtschaftlichen Systeme zusammenhängen. Aus diesen Analysen hat sich die Forschungsdisziplin der Ungleichheitsforschung gebildet, die sich mit Lohnarbeit und deren Auswirkungen befasst [für ein aktuelles Beispiel siehe @kohlrauschNeueArbeitNeue2019]. Neben diesen soziologischen Analysen wurde der Stellenwert von Arbeit auch immer wieder in philosophischen Debatten thematisiert. Ein zentraler Beitrag stammt etwa von Hannah Arendt, die in den 1950er-Jahren die Frage aufwarf, ob der Gesellschaft die Arbeit ausgehe und sich die Gesellschaft dadurch grundlegend verändern werde [@arendtVitaActivaOder1960]. EEin anderer bekannter Beitrag stammt von Bertrand Russell. Russell schreibt in den 1930er-Jahren über die schlechte Verteilung von Arbeit. Personen müssten ihm zufolge nur vier Stunden pro Tag arbeiten, wenn die Arbeit richtig verteilt werden würde. Der Weg hin zu weniger Arbeit bringt quasi die Befreiung des Menschen mit sich. Für Russell führen weniger Arbeit und die damit einhergehende Ausdehnung von freier Zeit direkt zur Vermeidung weiterer Probleme wie zum Beispiel Krieg oder Neid [@russellPraiseIdleness1932].  Ähnlich hoffnungsvolle Prognosen finden sich auch in aktuellen Debatten rund um heutige Arbeitsbedingungen. Mit dem Aufkommen des Internets und der Digitalisierung der Gesellschaft ist auch der Begriff der Arbeitswelt/Industrie 4.0 aufgekommen. Auch wenn dieser Begriff immer wieder kritisiert wird, sind damit doch viele Hoffnungen verbunden. So argumentieren Flecker et al., dass die Digitalisierung unter den richtigen Voraussetzungen (humanzentrierte Entwicklung) zu einer besseren Vereinbarkeit von Lohnarbeit und Privatleben führen könne, da die Automatisierung von Jobs mühsame Arbeiten von Menschen übernehmen und dadurch die Voraussetzungen schaffen könne, weniger zu arbeiten oder sich weiterzubilden [@fleckerDigitalisierungArbeitWelche2016]. Auch aus feministischer Perspektive ist die Digitalisierung eine Möglichkeit für Veränderungen mit dem Potential, die Bedingungen für FLINTAQ Personen zu verbessern [@hauerDigitalisierungSelbstlaeuferRichtung2016]. Eine empirische Arbeit von Watson et al. zeigt auf, dass der Zugang zu Internet eine positive Auswirkung für Frauen [sic!] auf dem Arbeitsmarkt hat [@watsonDigitalisationWomenWorkforce2018]. Neben der Digitalisierung und der technischen Entwicklung zeigte auch die COVID-19-Pandemie in den letzten Jahren Veränderungen an den Arbeitsverhältnissen auf. Einer der zentralsten Punkte war dabei die Möglichkeit zum Homeoffice. Studien deuten zum Beispiel auf positive Auswirkungen auf die Zufriedenheit (*well-being*) von Eltern hin [@canales-romeroJugglingSchoolWork2022] oder beobachten eine ausgeglichenere räumliche Verteilung der Beschäftigungsquoten (z.B. zwischen Ost- und Westdeutschland) [@garnadtRaeumlicheFlexibilisierungDurch2020]. 

Aber nicht alle sind von solchen hoffnungsvollen und positiven Entwicklungen überzeugt. Es gibt schon grundsätzliche Gegenthesen zu den Ansichten von Arendt und Russel. Dieter Sauer schreibt in einem Artikel vom weiteren bestehen der Arbeitsgesellschaft und der Wichtigkeit der Erwerbstätigkeit für den grössten Teil der Bevölkerung [@sauerZukunftArbeitsgesellschaftSoziologische2007]. Die Arbeit geht der Gesellschaft nicht aus und die Arbeit wird auch weiterhin eine der wichtigsten Lebensgrundlagen, wenn nicht sogar die wichtigste, sein. Auch in der aktuellen Debatte sind nicht alle von grundsätzlich positiven Entwicklungen überzeugt. Die Argumente, dass die Digitalisierung mehr Inklusion und Verminderung von Ungleichheit bedeutet, werden nicht gestützt. Sebastian Voigt schreibt sogar vom Gegenteil: Die Berufe der Mittelklasse gehen seit den 70er Jahren immer wie stärker verloren. Es gibt sozusagen eine Spaltung des Arbeitsmarkt in Hoch- und Niedriglohnsektoren [@voigtWandelArbeitsweltOekonomische2018]. Auch der Aufstieg zwischen den verschiedenen Berufsklassen und Schichten ist schwieriger geworden [@groh-samberEndeAufstiegsgesellschaft2015]. Voigt schreibt von der Auflösung des typischen männlichen Arbeitsverhältnis seit den 70er Jahren. Wie oben beschrieben, gibt es dank dieser Entwicklung auch Hoffnungen für die Besserstellung von FLINTAQ Personen. Aber dieser Besserstellung stehen trotzdem noch einige Hindernisse im Weg. So schreiben Watson et al. im bereits zitierten Beitrag zwar von einer Verbesserung dank Internetzugang, aber dennoch weiteren grossen strukturellen Barrieren für die Gleichstellung. Sie nennen unter anderem Faktoren wie den Zugang zu technischen Mitteln, patriarchalischen Normen und Einbindung in die technischen Branchen [@watsonDigitalisationWomenWorkforce2018, S.61 ff.]. Auch Gerlinde Hauer schreibt von der schlechten Repräsentation von Frauen in der ICT Branche, obwohl da so viel Potential bestehen würde [@hauerDigitalisierungSelbstlaeuferRichtung2016, S.175 ff.]. Die Autor:innen Möhring et al. zeigen, dass die Kurzarbeit vor allem Mütter und Personen ohne Kinder belastet. Väter sind kaum negativ betroffen oder empfinden die Entwicklung sogar als positiv [@mohringCOVID19PandemicSubjective2021]. Eine weitere Kritik an den Entwicklung ist die Möglichkeit zur Überwachung der Arbeitnehmenden. Ein solcher Beitrag für den deutschen Sprachraum, mit Fokus auf Österreich, findet sich bei Wolfie Christl [@christlDigitaleUberwachungUnd2021]. Für Schlagzeilen in diesem Bereich sorgen immer wieder Beiträge zu den schlimmen Arbeitsbedingungen in den Amazon Lagerhäusern.^[<https://www.theguardian.com/technology/2020/feb/05/amazon-workers-protest-unsafe-grueling-conditions-warehouse>] Insgesamt finden sich nebst den zahlreichen Hoffnungen auch viele Zweifel und offene Fragen.

In vielen der oben erwähnten Beiträgen findet sich der Begriff oder zumindest das Konzept von Flexibilisierung der Arbeit. Durch die technischen Entwicklungen oder die Verschiebung der Arbeit ins Homeoffice wird es möglich, andere Bereiche des Lebens besser mit der Lohnarbeit zu koordinieren. Die Flexibilisierung kann zur besseren Kontrolle und Einteilung der Zeit führen. Auch bei der Digitalisierung wird immer wieder mit dem Begriff von Zeit argumentiert. Zum Beispiel führt die Automatisierung von Arbeit zur Möglichkeit, die freigewordene Zeit nicht mehr mit Lohnarbeit verbringen zu müssen. In den Beiträgen von Hauer und Flecker wird die Reduktion der Arbeitszeit als eines der wichtigsten Mittel für die effektive Nutzung des technischen Fortschritts genannt [@fleckerDigitalisierungArbeitWelche2016; @hauerDigitalisierungSelbstlaeuferRichtung2016]. Dass die Debatte um die Arbeitszeit aktuell ist, zeigt auch ein kurzer Blick in die politische Landschaft der Schweiz. Zur Zeit sind zwei Vorstösse in der Stadt Zürich^[Die erste Motion fordert ein Pilotprojekt der 35h-Woche in für städtische Angestellte. Der zweite Vorstoss fordert eine Überprüfung eines solchen Pilotprojekts für die Privatwirtschaft.  <https://daslamm.ch/einer-der-wichtigsten-kaempfe-der-internationalen-linken/>] und eine im Nationalrat offen.^[Die Nationalrätinnen Funiciello (SP) und Prezioso Batou (Grüne) fordern mit der Motion 21.4642 die Reduktion der Arbeitszeit innert 10 Jahren auf maximal 35 Stunde pro Woche. Die Argumente sind die ineffiziente Verteilung von Erwerbsarbeit und Carearbeit, positive gesundheitliche Entwicklungen bei weniger Arbeitszeit und eine positive Auswirkung aufs Klima. <https://www.parlament.ch/de/ratsbetrieb/suche-curia-vista/geschaeft?AffairId=20214642>] Aber schon 1998 wurde von Nationalrat Rennwald (SP) eine Initiative zur Viertagewoche eingereicht. ^[In der Initiative 98.447 fordert Rennwald die Arbeitszeitbegrenzung auf 32 - 36 Stunden pro Woche bei vollem Lohnausgleich für Löhne unter (1.5x tiefer) dem durchschnittlichen Bruttoeinkommen <https://www.parlament.ch/de/ratsbetrieb/suche-curia-vista/geschaeft?AffairId=19980447>] Die Initiativen von Rennwald blieb erfolglos und auch für den Vorschlag von Funiciello und Prezisio Batou schlägt der Bundesrat vor die Motion abzulehnen. Die Antworten des Stadtrats für die Initiativen in Zürich stehen noch aus. Nebst der Debatten in der Schweiz wird auch in anderen europäischen Ländern die Frage um die Arbeitszeit aufgeworfen. In Belgien wurde im Frühling dieses Jahres die Viertagewoche umgesetzt.^[ <https://www.forbes.com/sites/annakaplan/2022/02/15/belgium-becomes-latest-country-to-let-workers-try-four-day-work-week/?sh=77edbe254990>.] Auch in Island wurde dank einer Studie von Haraldsson und Kellam die 35-Stundenwoche eingeführt [@haraldssonGoingPublicIceland2021].^[<https://www.srf.ch/news/wirtschaft/35-stunden-woche-fuer-alle-island-schaltet-auf-die-vier-tage-woche-um>] Demgegenüber stehen politische Forderungen im Raum, die eine Verlängerung der Arbeitszeit verlangen. ^[Siehe dazu die Diskussionen in Deutschland <https://www.zeit.de/arbeit/2022-06/fachkraeftemangel-4-tage-woche-42-stunden-woche-arbeitszeit>] 

Mit dieser Arbeit möchte ein Beitrag zu den aktuellen Debatten geleistet werden. Dies soll durch die Analysen von vergangenen Arbeitszeitdiskussionen in der Schweiz erreicht werden. Dafür werden zwei computergestützte Textanalysen durchgeführt. Das Ziel ist die explorative Untersuchung der Mitgliederkommunikation von zwei Verhandlungsparteien, die massgeblich an der Arbeitszeitverkürzungsdebatte in der Schweiz beteiligt waren. Dafür werden die Zeitschriften der beiden Verbände *Schweizerischer Gewerkschaftsbund* und *Zentralverband schweizerischer Arbeitgeber-Organisationen* in den Jahren 1930 - 1970 analysiert. Die Auswahl dieses Zeitraums hat mehrere Gründe: Erstens stammt die einzige rechtliche Regulierung der Arbeitszeit, die für alle Arbeitnehmer:innen gilt, aus dem Arbeitsgesetz von 1964. Die Festschreibung der Wochenarbeitszeit in einem branchen- und sektorübergreifenden Gesetz ist ein einmaliger Kompromiss in der Geschichte der Schweiz. Zweitens gab es in den 1950er Jahren zwei Initiativen zur Arbeitszeitverkürzung, was die Aktualität dieses Themas in dieser Zeitphase wiederum bestätigt. Drittens gab es in den 30er Jahren zwei wichtige Ereignisse, welche die Verhandlungen beeinflussten: Das Friedensabkommen von 1937 und das Durchsetzten des GAV als Mittel zur Arbeitszeitregulierung. Als letzter Punkt ist aufzuführen, dass es bereits einige Forschungsliteratur zur Arbeitszeitdiskussion in diesem Zeitraum gibt. Die Ergebnisse dieser Arbeit können somit gegen die bereits gewonnen Erkenntnisse geprüft werden. Da in den aktuellen Forderungen auch eine gsetzliche Festsetzung der Arbeitszeit verlangt wird, können die Erkenntnisse der Arbeit zum Kompromiss von 1964 die aktuellen Debatten unterstützen. Der Fokus auf bisher wenig beachtete empirische Quellen soll ausserdem zur wissenschaftlichen Erforschung dieses Themas beitragen. Im ersten Teil wird eine genauere Beschreibung des Begriffs der Arbeitszeit vorgenommen. Ausserdem wird spezifisch auf die rechtlichen und politischen Entwicklungen der Arbeitszeit in der Schweiz eingegangen. Im zweiten Teil folgt die Beschreibung des empirischen Materials und der angewendeten Methoden. Im Mittelpunkt steht dabei die explorative Erforschung der Zeitschriften mit der Latent dirichlet allocation (LDA). Im dritten Teil folgt die Darstellung der Resultate, die dann im vierten Teil diskutiert werden. Im abschliessenden fünften Teil der Arbeit findet sich das Fazit.
