# Diskussion

Die Diskussion der Analysen in dieser Arbeit erfolgt in zwei Schritten. Im ersten Teil werden die Resultate aus dem vorherigen Kapitel interpretiert und diskutiert. Im zweiten Teil wird auf mögliche Probleme und Schwierigkeiten der Analysemethoden eingegangen.

## Resultate

In den Resultaten ist zu sehen, dass einige der Themen aus dem theoretischen Teil in den Zeitungen vorkommen. Wie schon festgestellt worden ist, wird die Arbeitszeit meistens in Kombination mit anderen Arbeitsbedingungen diskutiert. Im theoretischen Teil wurden speziell das Thema Ferien und Lohn hervorgehoben. Das Thema Ferien wurde in beiden Zeitungskorpora in einem eigenen Topic erkannt. In beiden Zeitschriften wurde das Thema vor allem in Zusammenhang mit der Rechtslage besprochen. Das Thema Lohn war weniger gut ersichtlich. Es war lediglich das Wort „Stundenverdienste“ im zweiten Topic des ZSAO-Korpus zu finden. Beim SGB fand sich kein Wort, dass auf Lohnverhandlungen hindeutet. Ein Thema, das dafür beim SGB besonders hervorstach, ist die Diskussion um die Arbeitsbedingungen von Frauen und Jugendlichen. In der Entwicklung bis zum Arbeitsgesetz wurde der Fokus auf die Arbeitsbedingungen von Frauen und Jugendlichen erwähnt. Trotzdem wurde nicht antizipiert, dass dieses Thema in der ausgewählten Zeitspanne noch so prävalent sein würde. Es wurde im Korpus ein ganzes Topic zur Diskussion der Arbeitsbedingungen von Frauen und Müttern herausgebildet. Über Jugendliche wurde vor allem im Zusammenhang mit der Rechtslage gesprochen. Beim ZSAO gab es keinen speziellen Fokus auf Jugendliche oder Frauen. Die empirischen Befunde liefern folglich einen Hinweis darauf, dass die Arbeitszeit immer in Zusammenhang mit anderen Arbeitsbedingungen besprochen und verhandelt wurde.

Die speziellen Charaktereigenschaften der Schweizer Arbeitszeitverhandlung waren in den Resultaten nicht ausgeprägt erkennbar. Die Wichtigkeit der volkswirtschaftlichen Lage war in den Topics noch am besten zu erkennen. Die Statistik-Topics, vor allem beim ZSAO, wiesen auf die Wichtigkeit von volkswirtschaftlichen Zahlen hin. Ob diese wirklich für die Argumentation gebraucht worden sind oder ob die Statistiken „rein“ informative Zwecke hatten, ist schwierig zu sagen. Auch der Arbeitsfrieden war kaum in den Topics erkennbar. Das Wort selber wurde in keinem der Topics angezeigt. Einzig das Streik-Topic des ZSAO (Nummer 10) wies auf dieses Thema hin. Es scheint, als wäre der Arbeitsfrieden und die Beachtung der volkswirtschaftlichen Lage nicht explizit in den Texten erwähnt worden. Dies deutet darauf hin, dass es vor allem charakterliche Eigenschaften waren, welche die Diskussion oder Verhandlungen als eine Art Bias beeinflussten. Beide Faktoren steuerten zur konservativen arbeitszeitpolitischen Haltung in dieser Zeit bei.

Die Arbeitsmigrant:innen wurden im ZSAO-Korpus im Topic 4 erwähnt („ausländischen“), im SGB-Korpus gar nicht. Das Thema scheint somit in den Zeitschriften nicht wirklich als Thema behandelt worden zu sein. Da das Wort in einem Statistik-Topic vorkam ist es ausserdem wahrscheinlich, dass lediglich über die Anzahl an Arbeitsmigrant:innen berichtet worden war. Inwiefern das Thema für die Verhandlungen der Verbände wichtig war, lässt sich hier nicht beurteilen. Es ist jedoch ein Indiz, dass die Thematik bei der Kommunikation mit den Mitgliedern keine wichtige Rolle gespielt hat. Die Ergebnisse unterstützen die These einer Überrepräsentation des „Überfremdungsdiskurses“ in der Forschungsliteratur.

Die beiden Korpora zeigen einige Gemeinsamkeiten bei den Topics auf. Eines der gemeinsamen Topics wurde schon besprochen: Die Diskussionen bezüglich Ferien spielte bei beiden Verbänden eine wichtige Rolle. Ein weiteres gemeinsames Topic war die Berichterstattung rund um die Aktivität der Verbände. Hier wird eine Annahme aus dem theoretischen Teil bestätigt. Die Arbeitnehmer:innen- und Arbeitgeber:innenverbände sind politische Organisationen des dritten Sektors, die ihre Mitglieder behalten müssen oder neue Mitglieder gewinnen wollen. Damit dies gelingt, müssen die Verbände aktiv sein (Mitgliederlogik) und das politische Geschehen im Sinne der Mitglieder beeinflussen können (Einflusslogik). 

Eine dritte Gemeinsamkeit war der Fokus auf die Rechtslage der bestehenden Arbeitsbedingungen. Auch wenn beide Verbände unterschiedliche Themen öfters erwähnten, schien der Bezug auf die Rechtslage sehr wichtig zu sein. Im theoretischen Teil wurde gezeigt, wie selten eine rechtliche Festlegung der Arbeitszeit stattgefunden hat. Auch bei den Gesetzen über Ferien und zu den Arbeitsbedingungen für Jugendliche und Frauen fanden sich nur einige rechtliche Abmachungen. Einerseits könnten sich diese Topics herausgebildet haben, da Meinungen zu den Gesetzen formuliert worden sind. Andererseits, und dies ist erkenntnistheoretisch interessanter, könnte es zeigen, wie wichtig die Gesetze für eine weitere Diskussion der Arbeitszeit waren. Falls in den Texten immer wieder Bezug auf die bestehenden Regelungen gemacht wurde, war die gesetzliche Festlegung der Arbeitszeit die Grundlage von weiteren Diskussionen. Somit wurde mit den Gesetzen nicht nur der Fortschritt festgehalten, sondern sie dienten gewissermassen auch als ein Anker der als vernünftig geltenden Arbeitszeit in den Verhandlungen.

Ein sehr wichtiges Topic in beiden Korpora, war das Thema mit dem Titel „Mehr“. In beiden Korpora hatte dieses Topic regelmässig einen Anteil von 30–40%. Die beiden Topics sind jedoch nicht einfach zu interpretieren. Aus Sicht der Arbeitnehmer:innen wäre es sinnvoll zu erwarten, dass sie eine Entwicklung zu mehr Arbeit empfunden haben oder sehen konnten. Es machte jedoch aufseiten der Arbeitgeber:innen keinen Sinn, dies so zu formulieren. Auf Arbeigeber:innenseite wäre eine Bemängelung von mehr Freizeit sinnvoll gewesen. Wiederum machte dies aber keinen Sinn für die Arbeitnehmer:innen. Daher ist es am sinnvollsten diese Topics nicht nach wörtlichem Sinn zu interpretieren, sondern eher das Gefühl daraus zu verstehen. Die Verhandlungen um die Arbeitszeit war für beide Seiten mit viel Aufwand und Mühe verbunden. Dabei waren die Standpunkte der beiden Seiten klar und im Widerspruch zueinander: Eine Seite wollte mehr oder gleichbleibende Arbeitszeit, die andere Seite wollte weniger Arbeitszeit.^[Dies ist eine Vereinfachung der ganzen Debatte um die Arbeitszeit. Natürlich gab es auf beiden Seiten andere Meinungen. Zum Beispiel wurde bei Wirtschaftskrisen von Arbeitnehmer:innen das Recht zur Arbeit gefordert. Die Arbeitgeber:innen haben ausserdem immer wieder gezeigt, dass sie bei den richtigen Voraussetzungen weniger Arbeitszeit gutheissen.] Beide Seiten haben aus ihrer Sicht schon viel für die momentane Situation gegeben. Negative Wörter wie „müssen“ und „immer“ sprechen für eine gewisse Frustration. Auch die Identifikation der eigenen Seite war in den Topics lesbar. Die Wörter „unserer“ (ZSAO) und „Arbeiterschaft“ (SGB) zeigen eine Identifikation mit einer Gruppe. Das Topic als einen Ausdruck der Frustration in der Debatte um die Arbeitszeit zu interpretieren scheint, ohne weitere qualitative Analyse, am sinnvollsten.

Eine letzte Gemeinsamkeit der beiden Korpora war die Erwähnung von Statistiken im Kontext des Arbeitsmarkts oder der Volkswirtschaft. Dies war vor allem im Korpus des ZSAO sehr stark ausgeprägt. Wie im theoretischen Teil gezeigt (siehe Kapitel 2.4.1) war die Verhandlung der Arbeitszeit von vielen wirtschaftlichen Faktoren abhängig. Michaelis nannte als wichtigste Faktoren den Beschäftigungsgrad, das Produktionsvolumen, die Höhe der Lohnsätze, der Unternehmensgewinne und des Realeinkommens. Die Resultate zeigen, dass in den Zeitschriften auf diese und weitere wirtschaftliche Grössen (wie z.B. Import und Export) Bezug genommen wurde. 

Die beiden Korpora zeigen aber auch einige Differenzen bei den Topics auf. Beim SGB waren zwei Topics vorhanden, die im anderen Korpus nicht vorkommen. Beim ZSAO waren es sogar vier. Eines dieser Topics beim SGB war das Topic 4. Der Gewerkschaftsbund berichtete regelmässig über die Aktivitäten der International Labour Organization. Wie dies auch im theoretischen Teil angetönt worden ist, waren die Verhandlungen zu Arbeitsbedingungen oder zu Arbeitszeit eine internationale Bewegung. Gerade beim Landesstreik von 1918 wurde ersichtlich, dass sich die Diskussionen um Arbeitszeit nicht durch Landesgrenzen abtrennen lassen. Auch in der aktuellen Debatte zur Viertagewoche ist dies gut erkennbar. Die Arbeitgeber:innen bevorzugten im Allgemeinen eine individuelle Verhandlung der Arbeitszeit. Dass der ZSAO nicht auf internationale Diskussionen einging, ist durchaus erwartbar. Das zweite Topic im SGB-Korpus befasste sich mit den Themen Automation und Freizeit. Dabei schien es vor allem um die Frage zu gehen, wie mit der erhöhten Produktivität umgegangen werden soll. Auch heute ist dies eine aktuelle Debatte. Mit der Automation von einigen Aufgaben wäre eine Arbeitszeitverkürzung theoretisch möglich. Dass in der Zeitschrift des ZSAO dieses Topic nicht vorkam, ist auch hier zu erwarten. Beim ZSAO-Korpus kam jedoch ein Topic mit einem Gegenargument vor. Die Arbeit sei ein Grundbedürfnis des Menschen und jede Person sollte arbeiten wollen. Im Beitrag von Kaufmann wurde von der Angst von mehr Freizeit berichtet [@kaufmannVierzigstundenwocheSchweizAnschaulichtheoretischer1960, S. 87 – 91]. Das Topic wird wahrscheinlich in dieser Argumentationslinie verortbar sein. Anhand dieser beiden Topics ist schön zu sehen, wie sich die beiden Verbände unterschiedlich zur Arbeitszeitfrage positioniert haben. Ein weiteres Thema, dass nur im ZSAO-Korpus zu finden war, betrifft die Diskussion der Arbeitszeitverkürzungsinitiativen des LdU und des SGB. Eigentlich wäre dieses Topic auch im Korpus des SGB zu erwarten. Hier könnte die unterschiedliche Grösse der beiden Korpora und die Anzahl der Topics entscheidend gewesen sein. Die beiden letzten Topics, die nur beim ZSAO vorkamen, wurden oben schon erwähnt. Es handelt sich um das Streik-Topic und die Erwähnung der Arbeitsmigrant:innen. Auch hier ist es schwierig theoretisch zu begründen, wieso diese Topics nur beim ZSAO vorkommen. Wie bereits beim Initativen-Topic könnte die Beschaffenheit des empirischen Materials ein Grund sein.

Nach der Interpretation der LDA-Ergebnisse können auch die Resultate der Sentiment-Analyse besser verortet werden. Der SGB berichtete jeweils mit stärker ausgeprägten Emotionen (sowohl negativ als auch positiv). Beim ZSAO waren die negativen und positiven Emotionen ausgeglichener. Ein Grund für diesen Unterschied könnte die Anzahl an Statistik-Topics sein. Beim ZSAO waren vier Statistik-Topics zu erkennen, beim SGB nur eines. Bei Statistiken wird eine objektive, rationale Sprache gebraucht. Stark ausgeprägte emotionale Wörter sind eher nicht zu erwarten. Der grössere Anteil dieser Topics beim ZSAO neutralisierte den Score. Beim SGB fehlte dieser neutralisierende Faktor, was zu stärkeren Fluktuationen des Scores führte. Insgesamt glich sich der Anteil an positiven und negativen Wörtern jedoch wieder aus. Über den gesamten Korpus gesehen gab es bei den beiden Verbänden keinen signifikanten Unterschied und es wurde sogar eher positiv über das Thema berichtet. Eine mögliche Erklärung sind die speziellen Eigenschaften der Mitgliederzeitungen. Wie bereits geschrieben könnten die Zeitungen einen wichtigen Teil zum Weiterbestehen der Verbände beigetragen haben. Es macht Sinn, dass vor allem über die Aktivität der Verbände berichtet wurde. Dies wurde (voraussichtlich) eher in positiver als negativer Sprache gemacht. Die negative Sprache wurde wahrscheinlich vor allem in den Texten, in denen die andere Seite erwähnt worden war, gebraucht. Ein Punkt, der gegen dieses Argument spricht, ist, dass die identifizierten Topics der Verbandsaktivitäten nicht allzu oft in den Korpora vorkamen. Es ist aber davon auszugehen, dass in den meisten Topics eine eher positive Sprache verwendet wurde.

## Probleme bei Methoden

Durch die Resultate werden einige Schwierigkeiten bei der Anwendung von computergestützten Textanalysen sichtbar. Die grösste Schwierigkeit besteht bei der Interpretation der Ergebnisse. Obwohl es möglich ist, Erklärungen für die unterschiedlichen Topics oder die Sentiment-Scores zu formulieren, ist es schwierig diese auf ihre Validität zu überprüfen. Gerade bei kleineren Auffälligkeiten ist es schwierig, die Resultate erklären zu können. So ist zum Beispiel der plötzliche Anstieg des Frauen-Topics beim SGB oder die negative Prägung der Kommunikation des ZSAO vor 1937 ohne weiteres Wissen nicht interpretierbar. Theoretisch ist es möglich, sogenannte Ad-hoc-Hypothesen zu formulieren. Doch genau solche Annahmen sollten in der wissenschaftlichen Arbeit nicht gemacht werden. In ihrem einflussreichen Beitrag von 2012 schreiben Boyd & Crawford über die Wichtigkeit von Theorie bei der Anwendung von Algorithmen [@boydCriticalQuestionsBig2012].^[Siehe auch @halavaisBiggerSociologicalImaginations2015 und @mcfarlandSociologyEraBig2016.] Das Wissen und die Theorie, die im zweiten Teil besprochen wurden, sind zentral für das Verständnis der Resultate. Doch auch dadurch können nicht alle Muster in den Daten erklärt werden. Das Ziel dieser Arbeit ist jedoch nicht die kausale Erklärung von Zusammenhängen oder die Erklärung aller Muster aus den Daten, sondern die explorative Untersuchung des empirischen Materials. Dabei kann auf Themen, die durch das Vorwissen interpretiert werden können, eingegangen werden. Andere Auffälligkeiten, wie zum Beispiel der Anstieg des Frauen-Topics beim SGB, können in weiteren Forschungsarbeiten bearbeitet werden. Ein Vorteil von computergestützten Textanalyseverfahren wird hier erneut aufgezeigt. Es war einfach möglich, eine grosse Menge an Text in einer relativ kurzen Zeit zu bearbeiten. Durch die explorative Bearbeitung der beiden Korpora können weitere qualitative Studien am selben Material durchgeführt werden, die den Fokus schon viel enger setzen können, als dies ohne diese Analysen der Fall gewesen wäre.

Neben den allgemeinen Problemen der Verfahren gab es auch spezifische Probleme, die sich beim empirischen Material gezeigt haben. Eines davon war die relativ gering Anzahl Texte, die nach dem Auswahlverfahren noch übrig geblieben sind. Gerade beim Arbeitnehmendenkorpus waren es noch knapp über 1’000 Seiten Text. Diese Menge an Textmaterial wäre auch für qualitative Methoden geeignet gewesen. Trotzdem war es wichtig, diese Vorsortierung durchzuführen. Ein Interessenspunkt im Forschungsprozess war herauszufinden, ob das Thema Arbeitszeit als Topic im gesamten Korpus aufzufinden ist. Dies musste dann aber schnell wieder verworfen werden, da die Prototype-Analyse zu viel Rechenleistung benötigt. Obwohl die Ausstattung des Computers ziemlich gut war, hat es nicht gereicht, um den gesamten Korpus der 40 Jahre zu verarbeiten. Dieses Problem kann zwar durch Cloud-Lösungen umgangen werden, es setzt aber finanzielle Mittel voraus. Wie Boyd und Crawford geschrieben haben, ist dies ein Faktor, der zu einem neuen „digital divide“ führt [@boydCriticalQuestionsBig2012, S. 674].

Aber nicht nur die Quantität der Texte, sondern auch die Qualität führte zu gewissen Problemen. So gab es einen Teil der Texte, der keinen wirklichen Bezug zum Thema hatte. Darunter fallen die Angaben zu den Zeitschriften oder die Liste der bereits herausgegeben Büchern. Im Korpus des SGB führte dies zu einem eigenen Topic und im Korpus des ZSAO zu Verzerrungen einiger Topics. Ein weiterer Problempunkt war die Homogenität der Texte, die sich daran zeigte, dass einige Wörter in mehreren Topics vorkamen. Als bei der Festlegung der Anzahl Topics mit einer höheren Anzahl an Topics experimentiert wurde, wurde schnell deutlich, dass sich viele davon sehr stark ähnlich waren. Durch die Homogenität des Korpus war es schwierig, die Resultate zu interpretieren und Differenzen zu erkennen. Dies wurde auch durch die Ergebnisse der Validitätsprüfung gezeigt. Für Personen ohne Vorwissen war es schwierig die Topics sprachlich voneinander zu trennen. Dadurch, dass einige Wörter in mehreren Topics vorkamen, war es trotz Vorwissen schwierig, alle Intruderwords richtig zu erkennen.
