# Fazit

Das Verhältnis zwischen Lohnarbeit und Gesellschaft hat sich in der Vergangenheit immer wieder geändert. In den letzten Jahren wurde dieses Verhältnis unter anderem durch die Digitalisierung und die Flexibilisierung der Arbeit geprägt. Ausserdem wurden (zum Teil) neue Bedenken aus feministischen und ökologischen Perspektiven lauter. Die politische Lage in Europa zeigt, dass eine Neuverhandlung der wöchentlichen Arbeitszeit vor der Tür steht oder bereits im Gange ist.

In dieser Masterarbeit wurde die letzte grosse Arbeitszeitdiskussion in der Schweiz behandelt. Ausschlaggebend war die Verabschiedung des Arbeitsgesetzes von 1964, in dem die Normalarbeitszeit auf 46 bzw. 50 Stunden festgelegt worden war. Dafür wurden die Mitgliederzeitschriften von zwei sogenannten Ordnungskräften, die massgeblich an der Verhandlung der Arbeitszeit beteiligt waren, analysiert. Auf der einen Seite war dies der Schweizerische Gewerkschaftsbund, auf der anderen Seite war es der Zentralverband Schweizerischer Arbeitgeber-Organisationen. Bei der Analyse der Zeitschriften wurden zwei computergestütze Textanalyseverfahren genutzt: die Sentiment-Analyse und die Latent Dirichlet Allocation (LDA). Mithilfe dieser Analysen war es möglich, die Ausgaben der beiden Zeitschriften zwischen 1930 und 1970 explorativ zu untersuchen. Das Ziel war dabei einerseits, die theoretischen Erkenntnisse aus anderen Forschungsarbeiten nachzuvollziehen oder zu hinterfragen, andererseits sollte durch den Fokus auf die Mitgliederzeitungen eine vernachlässigte Dimension der Arbeitszeitdiskussion erschlossen werden.

Aus den Resultaten wird ersichtlich, dass die Ergebnisse bisheriger Forschungsarbeiten nur zum Teil nachvollziehbar sind. Die aus der Literatur zusammengetragenen wichtigsten Einflussfaktoren auf die Arbeitszeitdiskussion wurden in den Korpora nur zum Teil behandelt. Der Fokus der Zeitschriften unterscheidet sich von diesen Themen, der grundsätzliche konservative Charakter kann aber auch in den Resultaten dieser Arbeit erkannt werden. Insgesamt wird jedoch vor allem der Unterschied zwischen den Themen in den Zeitschriften der Verbände und den politischen Verhandlungen der Verbände aufgezeigt. In der bisherigen Forschungsliteratur wurden unter anderem die Wichtigkeit der volkswirtschaftlichen Lage, des Arbeitfriedens und der Arbeitsmigrant:innen hervorgehoben. Im Gegensatz dazu fanden sich in den Zeitschriften andere Themen wie Hinweise auf die rechtliche Lage (vor allem für Jungendliche und Frauen oder Ferien), Berichte über die Aktivität der Verbände oder Ausdrücke von Frustration über die Arbeitszeitdebatte. In den Zeitschriften wurde je nach Verband zusätzlich auf andere Themen Bezug genommen. In der Zeitschrift des Schweizerischen Gewerkschaftbundes wurde regelmässig über die Aktivitäten der International Labour Organization berichtet. Ausserdem gab es Stellungsnahmen zum Thema Automation und mehr Freizeit. Beim Zentralverband Schweizerischer Arbeitgeber-Organisationen gab es einen stärkeren Fokus auf die innenpolitische Lage. Es wurde über die beiden Arbeitszeitverkürzungsinitiativen aus den 1950er Jahren geschrieben. Der ZSAO schrieb aussserdem über die Erwerbsarbeit als Grundbedürfnis. Eine Erklärung für diese Differenzen könnte der Zweck dieser Zeitschriften sein. Sie erfüllten die Aufgabe, die Mitglieder über die Anstrengungen und Erfolge der Verbände zu informieren. So sollten die Mitglieder durch diese Kommunikation weiterhin an die Verbände gebunden bleiben oder idealerweise sogar noch mehr Mitglieder gewonnen werden. Die Zeitschriften deckten damit die Mitgliederlogik von politischen Organisationen ab. Die Sentiment-Analyse zeigt, dass in den Zeitschriften eher über die Erfolge der Verbände berichtet wurde. Ausserdem kommunizierte der SGB emotionaler als der ZSAO. 

Aus methodologischer Sicht kann die Wichtigkeit von Theorie bei computergestützten Analysen ein weiteres Mal unterstrichen werden. Das Wissen über den Forschungsgegenstand und das empirische Material bildet die Grundlage für die Formulierung von Thesen. Ohne dieses theoretische Fundament ist es nicht möglich, aus dem Material soziologisch sinnvolle Erkenntnisse zu ziehen. Ausserdem verhindert das theoretische Fundament die Erklärung von Mustern mit Ad-hoc-Hypothesen. Mit dieser Arbeit wurde ein Grundstein für die weitere Erforschung der Mitgliederkommunikation der Arbeitgeber:innen- und Arbeitnehmer:innenverbände gelegt. Weitere Arbeiten können sich mit der qualitativen Erforschung der Arbeitszeitdiskussion in den Zeitschriften befassen. Eine weitere Möglichkeit wäre ein Vergleich mit der heutigen Kommunikation der Verbände vorzunehmen.

Die Untersuchung der historischen Debatte und der Auswirkung der ersten gesetzlichen Festlegung der Arbeitszeit lässt darauf schliessen, dass auch zukünftige Festlegungen einer verkürzten Arbeitszeit zweifelsohne einen grossen Einfluss auf die arbeitszeitpolitische Lage in der Schweiz haben werden, würde doch dadurch erst das zweite Mal eine Normalarbeitszeit gesetzlich für alle Arbeitnehmer:innen der Schweiz festgelegt werden. Auch würde, je nach Grösse der Verkürzung, der konservative Charakter, der die letzten 80 Jahre der Arbeitszeitpolitik geprägt hat, in Frage gestellt werden. Für die Verbände auf den beiden Seiten wird die Verhandlung rund um die Arbeitszeit ein wichtiger Faktor für die Bindung oder den Neugewinn von Mitgliedern sein. Gerade aus Sicht der Gewerkschaften könnte dies eine Chance sein, den negativen Trend der Mitgliederzahlen zu unterbinden und die neuen Generationen in die Organisationen zu integrieren.